spring.datasource.url=jdbc:postgresql://localhost:5432/project_db
spring.datasource.username=project_user
spring.datasource.password=Sofia123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8081

